package com.gridweaver.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.UuidGenerator;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.io.Serial;
import java.io.Serializable;
import java.time.Instant;
import java.util.UUID;

/**
 * Abstract base entity providing common audit fields for all domain entities.
 *
 * <p>Every entity in GridWeaver inherits:
 * <ul>
 *   <li>UUID primary key (database-generated)</li>
 *   <li>Audit timestamps ({@code createdAt}, {@code updatedAt})</li>
 *   <li>Soft-delete support ({@code deletedAt} — null means active)</li>
 *   <li>Optimistic locking via {@code @Version}</li>
 * </ul>
 *
 * <p>Implements {@link Serializable} for Redis caching compatibility.
 *
 * @author GridWeaver Team
 */
@Getter
@Setter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * UUID primary key — generated by the database for maximum portability.
     * Using IETF RFC 4122 random UUID strategy.
     */
    @Id
    @UuidGenerator
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "UUID")
    private UUID id;

    /**
     * Timestamp set automatically when the entity is first persisted.
     * Never updated after creation.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Timestamp automatically updated on every modification via JPA Auditing.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    /**
     * Soft-delete marker. When non-null, the entity is treated as deleted.
     * Repositories must filter {@code WHERE deleted_at IS NULL} in all queries.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    /**
     * Optimistic locking version field. Incremented by Hibernate on every UPDATE.
     * Prevents lost-update concurrency anomalies.
     */
    @Version
    @Column(name = "version", nullable = false)
    private Long version = 0L;

    /**
     * Returns {@code true} if this entity has been soft-deleted.
     *
     * @return {@code true} when {@link #deletedAt} is non-null
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Marks this entity as soft-deleted by setting {@link #deletedAt} to now.
     */
    public void softDelete() {
        this.deletedAt = Instant.now();
    }
}
